### ISSUE TITLE
Snap store badge is broken

### ISSUE THREAD

**Issue by Ph0enixKM** [amber-lang/amber-docs#55]
It's on [installation page](https://docs.amber-lang.com/getting_started/installation)

![image](https://github.com/user-attachments/assets/878a2f02-d894-43b6-b464-efe5d02bbb00)

**Comment by Mte90** [comment]
So the image https://snapcraft.io/static/images/badges/en/snap-store-black.svg is reachable by browser

On firefox I get this The resource at “https://snapcraft.io/static/images/badges/en/snap-store-black.svg” was blocked due to its Cross-Origin-Resource-Policy header (or lack thereof). See https://developer.mozilla.org/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)#

So I think that it's the case to remove the image as it is blocked by the source.
